dist: bionic
sudo: false
language: c
compiler: gcc

before_install:
  - sudo apt-get update -qq

install: 
  - wget http://ccl.cse.nd.edu/software/files/cctools-7.0.19-x86_64-centos7.tar.gz
  - tar -xvf cctools-7.0.19-x86_64-centos7.tar.gz
  - mv cctools-7.0.19-x86_64-centos7 ~/cctools

script:
  - make -C src/
  - make install -C src/
  - make clean -C src/
  - make test -C src/
  - ./src/test
  - test $? == 0 || exit 1
  - cd test
  - bash test.sh
  - test $? == 0 || exit 1
